### ISSUE TITLE
segfault when coroutine return type is used without `co_return` and `co_await`

### ISSUE THREAD

**Issue by luncliff** [iains/gcc-cxx-coroutines#2]
#### Given
* A function returns the type which can be used for coroutine.

#### When
* The function didn't use `co_await` and `co_return` in its body.
* The return type doesn't have member variable.

#### Then
* Segfault when the function is invoked.

### Condition?
The issue happens in release(optimized) build (`-O2`).

## Details

* Target Platform: x86_64 GNU/Linux
* System Info: Linux-4.9.184-linuxkit (Docker Image)

### GCC Version

* c++-coroutines 275422

```console
$ gcc-10 --version
gcc-10 (GCC) 10.0.0 20190906 (experimental) [c++-coroutines revision 275422]
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### Reproduction

Direct compiler invocation in the Docker Container.

```sh
git clone https://github.com/luncliff/coroutine --branch dev/gcc;
cd coroutine;
git checkout 4ea1a2d8;

# Test with Docker to prevent platform issue
# Map the filesystem volume to make generated files visible from outside
sudo docker pull luncliff/gcc:275422;
sudo docker run -it --rm   -w /code -v $(pwd):/code    luncliff/gcc:275422;
```

In the Docker conatiner, `gcc-10` is located in `/usr/local/bin`(visible through the `PATH`).
After `docker run`, the shell **must be connected into the test environment**. Like,
```console
root@fb27e2a1850b:/code#
```

Compile the source code with the `-O2` flag.

```console
root@fb27e2a1850b:/code# gcc-10 ./test/gcc_no_keyword_in_body.cpp -fcoroutines -std=gnu++2a -O2
./test/gcc_no_keyword_in_body.cpp: In function 'forget_frame no_keyword_coroutine()':     
./test/gcc_no_keyword_in_body.cpp:55:1: warning: no return statement in function returning non-void [-Wreturn-type]
   55 | }
      | ^
```

Like the test code below, the function doesn't have return statement. So the warning is expected.

The build output must be an executable.
```console
root@fb27e2a1850b:/code# ./a.out
Segmentation fault
root@fb27e2a1850b:/code# $?
bash: 139: command not found
```

* Travis CI build log
    * Debug: https://travis-ci.org/luncliff/coroutine/jobs/582320313#L743
    * Release: https://travis-ci.org/luncliff/coroutine/jobs/582320314#L753

### Backtrace

This issue doesn't have a backtrace from the compiler.

### Source Code

* [coro.h](https://github.com/iains/gcc-cxx-coroutines/blob/2fa2a3a9cc9cfe0d2c91134068538949ebb10cec/gcc/testsuite/g%2B%2B.dg/coroutines/coro.h): used the file of https://github.com/iains/gcc-cxx-coroutines/commit/2fa2a3a9cc9cfe0d2c91134068538949ebb10cec (N4830)
* /test/gcc_no_keyword_in_body.cpp: https://github.com/luncliff/coroutine/blob/4ea1a2d8e0a9760349b962c2190368bed8a6ba45/test/gcc_no_keyword_in_body.cpp
```c++
//
//  Note
//    A coroutine function returns a type which fulfills
//    the Coroutine Promise Requirement,
//    but it forgot to use `co_await` or `co_return` in its definition
//
#include "coro.h"

using namespace std;
using namespace std::experimental;

class promise_nn {
  public:
    auto initial_suspend() noexcept {
        return suspend_never{};
    }
    auto final_suspend() noexcept {
        return suspend_never{};
    }
    void unhandled_exception() noexcept(false) {
    }
};

class forget_frame {
  public:
    class promise_type final : public promise_nn {
      public:
        void return_void() noexcept {
        }
        auto get_return_object() noexcept -> forget_frame {
            return {this};
        }
        static auto get_return_object_on_allocation_failure() noexcept
            -> forget_frame {
            return {nullptr};
        }
    };

  private:
    forget_frame(const promise_type*) noexcept {
        // the type truncates all given info about its frame
    }

  public:
    forget_frame() noexcept = default;
};

auto no_keyword_coroutine() -> forget_frame {
    // use coroutine's return type, but no `co_await` or `co_return`
}

int main(int, char* []) {
    no_keyword_coroutine();
    return 0;
}
```

**Comment by iains** [comment]
Thank you for your reports!

As a general comment, I am a bit puzzled by the use of lambda style for your function definition examples, this is not something I see anywhere else.

====

I don't think this is a compiler bug at all.

1) it's not a coroutine *unless* a keyword is present - that's what the standard demands (although personally I would prefer markup on the fn. definition to indicate its a coroutine).
 - therefore the fact that the function is meant to return a class which is nominally a coroutine isn't, I think, relevant.

... so comment 2 would apply completely independently of -fcoroutines (I can confirm that no coroutine-specific code is generated for this case).

2) The user's code is trying to invoke a function with no return value, ISTM that the compiler (with suitable optimisation in place) is determining this to be UB: and the resulting simple looks like this:

no_keyword_coroutine ()
{
  __builtin_unreachable ();
}

main (int D.2643, char * * D.2644)
{
  struct forget_frame D.2647;
  int D.2649;

  no_keyword_coroutine ();

  D.2649 = 0;
  return D.2649;
}

the "__builtin_unreachable()" is manifesting as an illegal insn - or a sego (it's UB to reach an unreachable, so all bets are off).

**Comment by luncliff** [comment]
I see. I knew that the code is a subroutine, but couldn't sure about the the reason of segfault.

closing the issue.
