### ISSUE TITLE
`get_return_object_on_allocation_failure` suppresses `get_return_object`

### ISSUE THREAD

**Issue by luncliff** [iains/gcc-cxx-coroutines#3]
#### Given
* A `promise_type` defines both `get_return_object` and `get_return_object_on_failure`.

#### When
* (normal) Its owner(which nests the `promise_type`) is used as a coroutine's return type.

#### Then
* `get_return_object_on_failure` is invoked instead of `get_return_object`

## Details

* Target Platform: x86_64 GNU/Linux
* System Info: Linux-4.9.184-linuxkit (Docker Image)

### GCC Version

* c++-coroutines 275422

### Reproduction

Direct compiler invocation in the Docker Container.

```sh
git clone https://github.com/luncliff/coroutine --branch dev/gcc;
cd coroutine;
git checkout 1dd075c8;

# Test with Docker to prevent platform issue
# Map the filesystem volume to make generated files visible from outside
sudo docker pull luncliff/gcc:275422;
sudo docker run -it --rm   -w /code -v $(pwd):/code    luncliff/gcc:275422;
```

In the Docker conatiner, `gcc-10` is located in `/usr/local/bin`(visible through the `PATH`).
After `docker run`, the shell **must be connected into the test environment**. Like,
```console
root@70db8004acb4:/code#
```

The test executable returns line number(`__LINE__`) as its status code to indicate that an assertion is failed.

```console
root@70db8004acb4:/code# gcc-10 ./test/gcc_memory_scenario_1.cpp -fcoroutines -std=gnu++2a -lstdc++ 
root@70db8004acb4:/code# ./a.out 
get_return_object_on_allocation_failure
preserve_frame: (nil)
after invoke: (nil) (null)
root@70db8004acb4:/code# $?
bash: 73: command not found
```

* Travis CI build log
    * Debug: https://travis-ci.org/luncliff/coroutine/jobs/582337807#L775
    * Release: https://travis-ci.org/luncliff/coroutine/jobs/582337808#L776

### Backtrace

This issue doesn't have a backtrace from the compiler.

### Source Code

* [coro.h](https://github.com/iains/gcc-cxx-coroutines/blob/2fa2a3a9cc9cfe0d2c91134068538949ebb10cec/gcc/testsuite/g%2B%2B.dg/coroutines/coro.h): used the file of https://github.com/iains/gcc-cxx-coroutines/commit/2fa2a3a9cc9cfe0d2c91134068538949ebb10cec (N4830)
* [test/gcc_memory_scenario_0.cpp](https://github.com/luncliff/coroutine/blob/1dd075c8824ec8f742ec03d22fe25c057415a3ca/test/gcc_memory_scenario_0.cpp): the code which doesn't define `get_return_object_on_allocation_failure`. 
* [test/gcc_memory_scenario_1.cpp](https://github.com/luncliff/coroutine/blob/1dd075c8824ec8f742ec03d22fe25c057415a3ca/test/gcc_memory_scenario_1.cpp#L40): the test code for this issue.

By the suppression, the control flow bypasses the coroutine's body.

```c++
//
//  Note
//    Memory allocation scenario - 1
//      Provides the function to handle allocation failure
//
#include <cstdio>

#include "coro.h"

using namespace std;
using namespace std::experimental;

class promise_return_preserve {
  public:
    auto initial_suspend() noexcept {
        return suspend_never{};
    }
    auto final_suspend() noexcept {
        return suspend_always{};
    }
    void unhandled_exception() noexcept {
    }
};

class preserve_frame final : public coroutine_handle<void> {
  public:
    class promise_type final : public promise_return_preserve {
      public:
        void return_void() noexcept {
        }

        auto get_return_object() noexcept -> preserve_frame {
            puts(__FUNCTION__);
            return preserve_frame{this};
        }
        static auto get_return_object_on_allocation_failure() noexcept
            -> preserve_frame {
            puts(__FUNCTION__);
            return preserve_frame{nullptr};
        }
    };

  private:
    explicit preserve_frame(promise_type* p) noexcept
        : coroutine_handle<void>{} {

        printf("%s: %p\n", __FUNCTION__, p);
        if (p == nullptr)
            return;

        coroutine_handle<void>& ref = *this;
        ref = coroutine_handle<promise_type>::from_promise(*p);
    }
};

auto store_after_await(const char** label) noexcept -> preserve_frame {
    co_await suspend_never{};
    *label = __FUNCTION__;
    co_return;
}

int main(int, char* []) {
    const char* label = nullptr;
    auto frame = store_after_await(&label);
    printf("after invoke: %p %s\n", frame.address(), label);

    if (frame.address() == nullptr)
        return __LINE__;

    frame.destroy();
    return 0;
}
```

**Comment by iains** [comment]
Actually, the problem is not that the g_r_o_o_a_f masks the g_r_o method, but that the compiler is failing to look up:
`void* operator new(std::size_t, const std::nothrow_t&) noexcept`

when the `<new>` header is missing.  This is causing the allocation to fail always.

If you add `#include <new>` your code will behave as expected.

Now I need to check:
 * if that operator version is supposed to be available without the header
  - if so, then this might be a GCC bug (or I might be making a lookup error)
  
 * if the operator is not required to be available without the header, then I should issue a diagnostic when it's missing.

**Comment by iains** [comment]
#include <new>, of course

**Comment by iains** [comment]
"<new>"

**Comment by iains** [comment]
heh.. it seems that markdown doesn't like that you need the 'new' header.

**Comment by iains** [comment]
looking at the standard, it seems that the `void* operator new(std::size_t, const std::nothrow_t&) noexcept` method is not implicitly available to a TU, the `<new>` header (or some other definition of the replaceable operator) is required.

So ... it seems that we could issue a diagnostic if the operator cannot be found .. I'll look at this at some stage.  Right now, the logic of the implementation appears to be correct.

**Comment by luncliff** [comment]
Thanks. I will try again with the header within 2~3 days :)

**Comment by luncliff** [comment]
With the `<new>` header, the logic indeed works correctly.

```c++
#include <new> // <---- N4830, 9.4.4 Coroutine deﬁnitions, item 10
// ::operator new(size_t, nothrow_t) noexcept is required

#include "coro.h"
```

So g_r_o_o_a_f has an implicit relation with the `std::nothrow_t`, and the library(or module) developers will be aware of the point... that seems enough for now IMO.
